version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"  # Exposing the PostgreSQL port on the host machine
    networks:
      - mynetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for database data

  backend:
    image: mghr/backendpfe
    container_name: backendpfe
    depends_on:
      - db
    environment:
      DBHOST: db
      DBNAME: mydatabase
      DBUSERNAME: myuser
      DBPASSWD: mypassword
    ports:
      - "8087:8080"
    networks:
      - mynetwork

  frontend:
    image: mghr/frontendpfe
    container_name: frontendpfe
    depends_on:
      - backend
    ports:
      - "8088:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres-data:  # Definition of the persistent volume
